### ISSUE TITLE
JSONDecodeError when trying to read Message from Hub

### ISSUE THREAD

**Issue by BuddhaOhneHals** [reinhard-brandstaedter/solarflow-control#335]
Hi,

first of all: thank you for your work! I have a Hub2000 + AB2000 + 4 panels running with solarflow-control and it's working really good.

But sometimes I get an JSONDecodeError exception when solarflow-control is trying to read a message from the Hub. After that exception occurs, no more messages from the Hub will be read. Solarflow-control keeps on working with the old data.

I have to manually restart the process.

Perhaps a generic exception handling in `handleMsg` could ensure that it keeps working?

Regards,
Timo

```
2024-12-28 09:25:00,798:INFO: HUB: S:56.0W [ 56.0,56.0 ], B: 21% (21) low: 20 high: 100, V:48.9V (48.9), C: 56W, P:False (auto, possible), F:42.2h, E:-1.0h, CT:ON (32hrs) discharging, H: 0W, L:700W
2024-12-28 09:25:00,799:INFO: INV: AC:0.0W, DC:0.1W (0.0|0.0), L:286W (142.8W/channel) [800W]
2024-12-28 09:25:00,799:INFO: SMT: T:Smartmeter P:134.0W [ 147.8,147.8,145.8,148.0,143.3 ]
2024-12-28 09:25:00,800:INFO: Direct connected panel are producing 0.0W, trying to get 143.3W from hub.
2024-12-28 09:25:00,802:INFO: Based on time, solarpower (56.0W) minimum charge power (100W) and bypass state (False), hub could contribute  0.0W - Decision path: 2.2.
2024-12-28 09:25:00,802:INFO: Not setting solarflow output limit to 700.0W as it is identical to current limit!
2024-12-28 09:25:00,802:INFO: Solarflow is willing to contribute 0.0W (per channel) of the requested 143.3!
2024-12-28 09:25:00,803:INFO: Inverter is not reachable/down. Can't set limit
2024-12-28 09:25:00,805:INFO: Sun: 08:37 - 16:31 Demand: 143.3W, Panel DC: (0.0W), Hub DC: (0.0W), Inverter Limit: 20.0W, Hub Limit: 700.0W
2024-12-28 09:25:02,406:INFO: Triggering telemetry update: iot/A8yh63/0MGPun5g/properties/read
2024-12-28 09:26:02,407:INFO: Triggering telemetry update: iot/A8yh63/0MGPun5g/properties/read
Exception in thread Thread-1 (_thread_main):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/opt/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/opt/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/solarflow/solarflow-control.py", line 166, in on_message
    hub.handleMsg(msg)
  File "/solarflow/solarflow.py", line 387, in handleMsg
    payload = json.loads(msg.payload.decode())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 152 (char 151)
2024-12-28 09:27:00,800:INFO: HUB: S:73.5W [ 73.5,73.5 ], B: 21% (21) low: 20 high: 100, V:49.0V (49.0), C: 71W, P:False (auto, possible), F:42.2h, E:-1.0h, CT:ON (32hrs) discharging, H: 0W, L:700W
2024-12-28 09:27:00,800:INFO: INV: AC:0.0W, DC:0.1W (0.0|0.0), L:286W (142.8W/channel) [800W]
2024-12-28 09:27:00,801:INFO: SMT: T:Smartmeter P:139.0W [ 134.3,134.3 ]
2024-12-28 09:27:00,801:INFO: Direct connected panel are producing 0.0W, trying to get 134.3W from hub.
2024-12-28 09:27:00,803:INFO: Based on time, solarpower (73.5W) minimum charge power (100W) and bypass state (False), hub could contribute  0.0W - Decision path: 2.2.
2024-12-28 09:27:00,803:INFO: Not setting solarflow output limit to 700.0W as it is identical to current limit!
2024-12-28 09:27:00,804:INFO: Solarflow is willing to contribute 0.0W (per channel) of the requested 134.3!
2024-12-28 09:27:00,804:INFO: Inverter is not reachable/down. Can't set limit
2024-12-28 09:27:00,806:INFO: Sun: 08:37 - 16:31 Demand: 134.3W, Panel DC: (0.0W), Hub DC: (0.0W), Inverter Limit: 20.0W, Hub Limit: 700.0W
2024-12-28 09:27:02,408:INFO: Triggering telemetry update: iot/A8yh63/0MGPun5g/properties/read
2024-12-28 09:28:02,410:INFO: Triggering telemetry update: iot/A8yh63/0MGPun5g/properties/read
2024-12-28 09:29:00,801:INFO: HUB: S:73.5W [ 73.5,73.5 ], B: 21% (21) low: 20 high: 100, V:49.0V (49.0), C: 71W, P:False (auto, possible), F:42.2h, E:-1.0h, CT:ON (32hrs) discharging, H: 0W, L:700W
2024-12-28 09:29:00,802:INFO: INV: AC:0.0W, DC:0.1W (0.0|0.0), L:286W (142.8W/channel) [800W]
2024-12-28 09:29:00,802:INFO: SMT: T:Smartmeter P:139.0W [ 134.3,134.3 ]
2024-12-28 09:29:00,803:INFO: Direct connected panel are producing 0.0W, trying to get 134.3W from hub.
2024-12-28 09:29:00,804:INFO: Based on time, solarpower (73.5W) minimum charge power (100W) and bypass state (False), hub could contribute  0.0W - Decision path: 2.2.
2024-12-28 09:29:00,805:INFO: Not setting solarflow output limit to 700.0W as it is identical to current limit!
2024-12-28 09:29:00,805:INFO: Solarflow is willing to contribute 0.0W (per channel) of the requested 134.3!
2024-12-28 09:29:00,806:INFO: Inverter is not reachable/down. Can't set limit
2024-12-28 09:29:00,808:INFO: Sun: 08:37 - 16:31 Demand: 134.3W, Panel DC: (0.0W), Hub DC: (0.0W), Inverter Limit: 20.0W, Hub Limit: 700.0W
2024-12-28 09:29:02,411:INFO: Triggering telemetry update: iot/A8yh63/0MGPun5g/properties/read
2024-12-28 09:30:02,413:INFO: Triggering telemetry update: iot/A8yh63/0MGPun5g/properties/read
2024-12-28 09:31:00,803:INFO: HUB: S:73.5W [ 73.5,73.5 ], B: 21% (21) low: 20 high: 100, V:49.0V (49.0), C: 71W, P:False (auto, possible), F:42.3h, E:-1.0h, CT:ON (32hrs) discharging, H: 0W, L:700W
2024-12-28 09:31:00,803:INFO: INV: AC:0.0W, DC:0.1W (0.0|0.0), L:286W (142.8W/channel) [800W]
2024-12-28 09:31:00,804:INFO: SMT: T:Smartmeter P:139.0W [ 134.3,134.3 ]
2024-12-28 09:31:00,804:INFO: Direct connected panel are producing 0.0W, trying to get 134.3W from hub.
2024-12-28 09:31:00,806:INFO: Based on time, solarpower (73.5W) minimum charge power (100W) and bypass state (False), hub could contribute  0.0W - Decision path: 2.2.
2024-12-28 09:31:00,806:INFO: Not setting solarflow output limit to 700.0W as it is identical to current limit!
2024-12-28 09:31:00,807:INFO: Solarflow is willing to contribute 0.0W (per channel) of the requested 134.3!
2024-12-28 09:31:00,807:INFO: Inverter is not reachable/down. Can't set limit
2024-12-28 09:31:00,809:INFO: Sun: 08:37 - 16:31 Demand: 134.3W, Panel DC: (0.0W), Hub DC: (0.0W), Inverter Limit: 20.0W, Hub Limit: 700.0W
2024-12-28 09:31:02,414:INFO: Triggering telemetry update: iot/A8yh63/0MGPun5g/properties/read
2024-12-28 09:32:02,416:INFO: Triggering telemetry update: iot/A8yh63/0MGPun5g/properties/read
2024-12-28 09:32:58,696:INFO: Publishing Homeassistant templates...
2024-12-28 09:32:59,435:INFO: Published 36 Homeassistant templates.
```

**Comment by reinhard-brandstaedter** [comment]
Thanks for reporting this error. Agree there should be some error handling here.
Though ai have never seen the hub reporting anything different than json…so it could well be that something else is reported at one of the topics.
I’ll add exception handling and reporting for that.
